version: "3.4"
services:
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    user: '1000:1000'
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_VERSION:-8.0.30}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33061:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"


