version: "3.8"
services:
  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    user: '1000:1000'
    volumes:
      - ./:/var/www/app
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data:rw
      - ./docker/dev/db:/docker-entrypoint-database.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass_db}
      POSTGRES_USER: ${POSTGRES_USER:-user_db}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database: ~